### ISSUE TITLE
http basic auth is broken

### ISSUE THREAD

**Issue by fmarani** [mozilla/django-piston#2]
When returning the challenge response and the 401 status, an exception is triggered. 
Exception is triggered because HttpBasicAuthentication::challenge() is called with two params instead of one.

This small patch solved the issue

<pre>
diff --git a/piston/authentication.py b/piston/authentication.py
index a11e260..f1b814a 100644
--- a/piston/authentication.py
+++ b/piston/authentication.py
@@ -63,7 +63,7 @@ class HttpBasicAuthentication(object):
 
         return not request.user in (False, None, AnonymousUser())
 
-    def challenge(self):
+    def challenge(self, request=None):
         resp = HttpResponse("Authorization Required")
         resp['WWW-Authenticate'] = 'Basic realm="%s"' % self.realm
         resp.status_code = 401
</pre>

method signature has been copied from OAuthAuthentication class..

**Comment by andymckay** [comment]
These patches should go upstream on the bitbucket repo, not into the mozilla repo. This was forked here so we could use our existing git tools to pull it into our builds.
